# Generated by Django 2.2 on 2019-06-01 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_archive', models.FileField(upload_to='dicom/')),
                ('patient_id', models.CharField(max_length=64, null=True)),
                ('study_uid', models.CharField(max_length=64)),
                ('series_uid', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Image Series',
            },
        ),
        migrations.CreateModel(
            name='SeriesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorComment', models.CharField(default='', max_length=256)),
                ('doctorCommentDate', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('seriesID', models.IntegerField()),
                ('slicesCnt', models.IntegerField()),
                ('AccessionNumber', models.CharField(max_length=128)),
                ('AcquisitionDate', models.CharField(max_length=128)),
                ('FilterType', models.CharField(max_length=128)),
                ('PatientID', models.CharField(max_length=128)),
                ('PatientAge', models.CharField(max_length=128)),
                ('PatientBirthDate', models.CharField(max_length=128)),
                ('PatientPosition', models.CharField(max_length=128)),
                ('StudyID', models.CharField(max_length=128)),
                ('PatientSex', models.CharField(max_length=128)),
                ('ScanOptions', models.CharField(max_length=128)),
                ('SeriesDate', models.CharField(max_length=128)),
                ('SeriesDescription', models.CharField(max_length=128)),
                ('SeriesTime', models.CharField(max_length=128)),
                ('SoftwareVersions', models.CharField(max_length=128)),
                ('StationName', models.CharField(max_length=128)),
                ('StudyDate', models.CharField(max_length=128)),
                ('StudyStatusID', models.CharField(max_length=128)),
                ('SeriesInstanceUID', models.CharField(max_length=128)),
                ('StudyTime', models.CharField(max_length=128)),
                ('Manufacturer', models.CharField(max_length=128)),
                ('previewSlice', models.CharField(default='0_gray.png', max_length=32)),
                ('slices_dir', models.CharField(max_length=128)),
            ],
        ),
    ]
