# Generated by Django 2.0.7 on 2019-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0002_auto_20190601_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageseries',
            name='dicom_archive',
        ),
        migrations.AddField(
            model_name='imageseries',
            name='dcm_meta',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageseries',
            name='slices_dir',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
