# Generated by Django 2.0.7 on 2019-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0003_auto_20190622_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesID', models.IntegerField()),
                ('maskName', models.CharField(max_length=64)),
                ('maskDescription', models.CharField(max_length=128)),
                ('maskFolder', models.CharField(max_length=64)),
                ('processProgress', models.IntegerField(default=0)),
            ],
        ),
    ]
