# Generated by Django 2.0.7 on 2019-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0004_predictionmask'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageseries',
            name='zipFilePath',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
