# Generated by Django 2.0.7 on 2019-06-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0005_imageseries_zipfilepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageseries',
            old_name='zipFilePath',
            new_name='zipFileName',
        ),
    ]
