# Generated by Django 2.0.7 on 2019-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0006_auto_20190622_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmask',
            name='fileName',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
