version: '3'


services:
  producer:
    build: ./producer
    environment:
      KAFKA_BROKER_URL: broker:9092

  consumer:
    build: ./consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions


networks:
  default:
    external:
      name: kafka-network
