version: "3"

services:
  django:
    build: 
      context: ./django
    ports:
      - "8001:8001"
      - "8000:8000"
    volumes:
      - ./django/app:/django
      - aimed_archives:/app/static/research_storage/zips
      - aimed_results:/app/static/research_storage/results
    command: >
      sh -c "uwsgi --ini radiology_uwsgi.ini"

  dnn_backend:
    build: ./dnn_backend
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: dnn.data
      KAFKA_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'

    volumes:
      - aimed_archives:/mnt/archives
      - aimed_results:/mnt/results
    ports:
      - "12222:22"


networks:
  default:
    external:
      name: kafka-network

volumes:
  aimed_archives:
  aimed_results:

