# Generated by Django 2.2.4 on 2019-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(auto_now=True)),
                ('study_time', models.TimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=128)),
                ('series_instance_uid', models.CharField(max_length=128)),
                ('series_number', models.CharField(max_length=128)),
                ('dicom_tags', models.TextField()),
                ('dicom_names', models.TextField()),
                ('dir_name', models.CharField(max_length=256)),
                ('zip_name', models.CharField(max_length=256)),
                ('preview_image', models.CharField(max_length=128)),
            ],
        ),
    ]
