# Generated by Django 2.2.3 on 2019-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(auto_now=True)),
                ('study_time', models.TimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=128)),
                ('series_instance_uid', models.CharField(max_length=128)),
                ('series_number', models.CharField(max_length=128)),
                ('dicom_tags', models.CharField(max_length=67108864)),
                ('dicom_names', models.CharField(max_length=67108864)),
                ('dir_name', models.CharField(max_length=256)),
                ('zip_name', models.CharField(max_length=256)),
            ],
        ),
    ]
