# Generated by Django 2.2.3 on 2019-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='preview_image',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
