version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper 
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    hostname: broker 
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      
  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "9999:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_LOG4J_ROOT_LOGLEVEL: 'ERROR'
      SCHEMA_TOOLS_LOG4J_LOGLEVEL: 'ERROR'

  schema_registry_ui:
    image: landoop/schema-registry-ui 
    depends_on:
      - schema_registry 
    ports:
      - "10001:8000"
    environment:
      SCHEMAREGISTRY_URL: 'http://schema_registry:8081'

  control-center:
    image: confluentinc/cp-enterprise-control-center
    hostname: control-center
    depends_on:
      - zookeeper
      - broker
      - schema_registry
    ports:
      - "9998:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      #CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
      CONTROL_CENTER_LOG4J_ROOT_LOGLEVEL: 'ERROR'
      CONTROL_CENTER_TOOLS_LOG4J_LOGLEVEL: 'ERROR'
  

  kafka-rest:
    image: confluentinc/cp-kafka-rest
    hostname: kafka-rest
    depends_on:
      - broker
      - schema_registry
    ports:
      - "10000:10000"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_HOST_NAME: 'kafka-rest'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:10000'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: 'ERROR'
      KAFKA_REST_TOOLS_LOG4J_LOGLEVEL: 'ERROR'

  kafka-topics-ui: 
    image: landoop/kafka-topics-ui
    hostname: kafka_topics_ui
    depends_on:
      - broker
    ports:
      - "9997:8000"
    environment:
      KAFKA_REST_PROXY_URL: 'http://kafka-rest:10000'
      PROXY: "true"

networks:
  default:
    external:
      name: kafka-network 
