# Generated by Django 2.0.7 on 2019-06-16 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('to', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
