# Generated by Django 2.2.3 on 2019-07-31 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20190622_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image_src', models.CharField(max_length=256)),
            ],
        ),
    ]
