version: '3'


services:
  auth:
    hostname: auth
    build:
      context: auth_aimed/.
      dockerfile: Dockerfile
    networks:
      - kafka-network
    depends_on:
      - db_auth
    volumes:
      - aimed_results:/mnt/results

  db_auth:
    networks:
      - kafka-network
    build:
      context: auth_aimed/database/.

  bot:
    build:
      context: bot_aimed/.
      dockerfile: Dockerfile
    environment:
      AUTH_URL: http://auth:8082/research
    volumes:
      - aimed_results:/mnt/results
    networks:
      - kafka-network


networks:
  default:
     external:
       name: kafka-network

volumes:
  aimed_results:
    external: true
